# Generated by Django 3.1.3 on 2021-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profiles/2021-07-20 13:20:30.218966/avatars/'),
        ),
    ]
